---
- name: Update web servers
  hosts: web
  gather_facts: False
   
  tasks:
  - name: Install the latest version of Apache
    yum:
      name=httpd
      state=latest
    when: ansible_os_family == "Debian"
  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: index.html
      dest: /var/www/html/index.html
  - name: Start service httpd, if not started
    ansible.builtin.service:
      name=httpd
      state=started
