---
- name: Update web servers
  hosts: web
  vars:
    packagename: httpd
    servicename: httpd
    name: sandy
    age: 23
  vars_files:
    - ext-vars.yaml
  vars_prompt:
    - name: "Version"
      prompt: "Which version Do you want to install?"
      private: false
   
  tasks:
  - name: Install the latest version of Apache
    yum:
      name={{ packagename }}
      state=latest
  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: index.html
      dest: /var/www/html/index.html
  - name: Start service httpd, if not started
    ansible.builtin.service:
      name={{ servicename }}
      state=started
  - name: include default step variables
    include_vars: var-include.yml
  - name: Print the vars
    ansible.builtin.debug:
      msg: My name {{ name }} and My age is {{ age }}
  - name: Print the vars
    ansible.builtin.debug:
      msg: Which version Do you want to install? {{ Version }}
  - name: Ansible register variable basic example
    shell: "find *.yaml"
    args:
      chdir: "/home/centos/ansible/sandhya"
    register: find_output
  - debug:
      var: find_output.stdout_lines[0]

