---
- name: Update web servers
  hosts: web
   
  tasks:
    - name: Include task list in play task1.yaml
      include: task1.yaml
    - name: Include task list in play task2.yaml
      include: task2.yaml
