---
  - name: Install webserver
  hosts: web
  vars:-
    packagename: httpd

  tasks:
  - name: Install the latest version of Apache
    yum:
      name={{ packagename }}
      state=latest
    when: ansible_os_family == "RHEL"
  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: index.html
      dest: /var/www/html/index.html
  - name: Start service httpd, if not started
    ansible.builtin.service:
      name=httpd
      state=started
  - name: Template a file to /etc/file.conf
    ansible.builtin.template:
      src: index.html.j2
      dest: /var/www/html/index.html
   notify:
      - Start service httpd, if not started
  - name: Start service httpd, if not started
    ansible.builtin.service:
      name=httpd
      state=started

  handlers:
  - name: Start service httpd, if not started
    ansible.builtin.service:
      name=httpd
      state=restarted
