---
- name: To start and enable httpd service
  hosts: web

  tasks:
  - name: start httpd
    service:
      name: httpd 
      state: started

  - name: enable httpd
    service:
      name: httpd 
      enabled: yes
