---
- name: Variable declarations
  hosts: web
  vars:
   packname: httpd
   myname: Priyanka Chowdary
   myage: 22
  vars_files:
   - var-declare.yml

  tasks:
  - name: Install Apache
    yum:
      name: "{{packname}}"
      state: latest
  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: index.html
      dest: /var/www/html/index.html
  - name: Start service httpd, if not started
    ansible.builtin.service:
      name: "{{packname}}"
      state: started
  - name: var include
    include_vars: var-include.yml
